<?xml version="1.0" encoding="ISO-8859-1"?>
<MessageDefinitions>
<Metadata generated="2006-04-03 11:34:40" releaseGlobal="YES" versionnr="3829"/>
<MSG COMP="Savepoint" ID="1" VERSION="1">
<DefineName>
REASON_INFO
</DefineName>
<ShortText>
Savepoint ($REASON$) started by T$TASK_ID$
</ShortText>
</MSG>
<MSG COMP="Savepoint" ID="2" VERSION="1">
<DefineName>
NOT_ALLOWED
</DefineName>
<ShortText>
Savepoint writing is currently not allowed. The reason is $REASON$.
</ShortText>
</MSG>
<MSG COMP="Savepoint" ID="3" VERSION="1">
<DefineName>
DENIED_BECAUSE_LOG_FULL_AND_HISTORY_LOST
</DefineName>
<ShortText>
The Savepoint is not allowed because the log is full and the backup history is lost.
</ShortText>
<Description><![CDATA[
The backup history was interrupted because the log was deleted (e.g. through CLEAR LOG, ACTIVATE+RESTORE, RESTORE/RESTART UNTIL). 
No log is allowed to be backed-up in this state.
Only a complete data backup restarts the backup history. 
Afterwards a log can and must be backed-up.
]]></Description>
<Action><![CDATA[
]]></Action>
</MSG>
<MSG COMP="Savepoint" ID="4" VERSION="1">
<DefineName>
SECOND_DBM_REASON
</DefineName>
<ShortText>
A second dbm command wants to trigger a savepoint. OldT$OLD_TASK_ID$ ($OLD_REASON$) NewT$TASK_ID$ ($REASON$)
</ShortText>
<Description><![CDATA[
A special savepoint request for a DBM command already exists. 
A second has now arisen which will not work.
]]></Description>
</MSG>
<MSG COMP="Savepoint" ID="5" VERSION="1">
<DefineName>
START_FAILED
</DefineName>
<ShortText>
The savepoint coordinator could not be started.
</ShortText>
<Action><![CDATA[
]]></Action>
</MSG>
</MessageDefinitions>
